export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST"
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS"
export const UPDATE_USER_STATUS_FAIL = "UPDATE_USER_STATUS_FAIL"

export const ORDER_GET_STATUS_REQUEST = "ORDER_GET_STATUS_REQUEST"
export const ORDER_GET_STATUS_SUCCESS = "ORDER_GET_STATUS_SUCCESS"
export const ORDER_GET_STATUS_FAIL = "ORDER_GET_STATUS_FAIL"
